### ISSUE TITLE
Sending images on chat

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-kotlin#180]
The chat actions menu is built and push to branch with name `tt/feature/chat-actions-menu` so you should start from there.
In `ChatViewModel.kt - showActionsMenu()` (Line 410) is the place to handle each menu item tap.

# Logic 

Once the image is taken and you have the Data for that image, we are creating a random string with a length of 32 and using some specific letter (same logic we use to generate the auth token but with different length) and using it to encrypt the data symmetrically using that key. 

At this point we are creating the provisional message record so the row shows on chat: 

https://github.com/stakwork/sphinx/blob/8d16f84c829792ef72485231f99978f47be0e184/sphinx/Core%20Data/TransactionMessage/TransactionMessage%2BCoreDataClass.swift#L343

Once we have the encrypted data and the key we are uploading encrypted data to memes-server using the following endpoint:
```
POST "https://memes.sphinx.chat/file"
- HTTPHeader "Authorization": "Bearer $token"
- MultipartFormData 
       1. "image" withName: "name"
       2. ImageEncryptedData withName: "file", fileName: "image.jpg", mimeType: "image/jpg"
- Response: fileJson with some information about the file that will be used to create sendAttachment params
```

Once upload finishes, a new request needs to be done to:
`- POST relayURL/attachment with same params as on sendMessage request and some other media params details on this link`

https://github.com/stakwork/sphinx/blob/8d16f84c829792ef72485231f99978f47be0e184/sphinx/Core%20Data/TransactionMessage/TransactionMessageParamsExtension.swift#L96

```
- "media_key_map": encrypted media key using the same logic as on "remote_text_map" on text message.
- "media_type" : "mime" value from fileJson returned on upload request
- "muid" : "muid" value from fileJson returned on upload request
```

# Flow screenshots

![IMG_0519](https://user-images.githubusercontent.com/2242281/123143286-c7c49500-d430-11eb-9237-ba2d93f16fc5.PNG)

When selecting Camera option it should take user to camera

![IMG_0520](https://user-images.githubusercontent.com/2242281/123143897-72d54e80-d431-11eb-8621-f7e19f607bc8.PNG)

After image is taken, it will move to image preview where user can set a PRICE and a MESSAGE. We can disabled price for now. 

![IMG_0521](https://user-images.githubusercontent.com/2242281/123143977-8aacd280-d431-11eb-9c5f-4a6ea7aa9132.PNG)

Finally image row is inserted into chat and on iOS we are showing an uploaded progress label on the row header. 

![IMG_0522](https://user-images.githubusercontent.com/2242281/123144075-a9ab6480-d431-11eb-87f6-d8e7178475da.PNG)

**Comment by 05nelsonm** [comment]
```
POST "https://memes.sphinx.chat/file"
- HTTPHeader "Authorization": "Bearer $token"
- MultipartFormData 
       1. "image" withName: "name"
       2. ImageEncryptedData withName: "file", fileName: "image.jpg", mimeType: "image/jpg"
- Response: fileJson with some information about the file that will be used to create sendAttachment params
```

Not too clear what 1 and 2 are as that looks like platform specific code.

Is "name" a static value used in the `Content-Disposition` header for the `name=`? (ex. name=name)
Is "image" the request body of the first part?

What are other acceptable types other than "image"? (ex. pdf, text, gif, audio, video)

**Comment by tomastiminskas** [comment]
@05nelsonm 

**- Is "name" a static value used in the Content-Disposition header for the name=?** 

_YES, But the example would be name=image_

**- Is "image" the request body of the first part?**

_YES_

https://github.com/Alamofire/Alamofire/blob/a41c07a558b508bcf3a66552c726cab5dda65501/Source/MultipartFormData.swift#L140

- **What are other acceptable types other than "image"? (ex. pdf, text, gif, audio, video)**

```
case .Photo, .Gif:
    return "image"
case .Video:
    return "video"
case .Audio:
    return "audio"
case .Text:
    return "text"
case .PDF:
    return "file"
case .GenericFile:
    return "file"
}
```

**Comment by tomastiminskas** [comment]
@05nelsonm 

And here are the possible values for fileName and mimeType. Being the first value of the Pair the fileName, and the second value the mimeType

```
case .Video:
    return ("video.mov", "video/mov")
case .Photo:
    return ("image.jpg", "image/jpg")
case .Audio:
    return ("audio.m4a", "audio/m4a")
case .Text:
    return ("message.txt", "sphinx/text")
case .Gif:
    return ("image.gif", "image/gif")
case .PDF:
    return (fileName ?? "file.pdf", "application/pdf")
case .GenericFile:
    return (fileName ?? "file", fileName?.mimeTypeForPath() ?? "file.txt")
```
