### ISSUE TITLE
Adding new contact

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-kotlin#201]
I added my hosted sphinx contact to my kotlin app (Add Friend > Already on Sphinx).
The contact saves, but when I try to send a msg, nothing shows in the chat and no message is received.

**Comment by tomastiminskas** [comment]
@pitoi I tried adding your hosted sphinx contact on my kotlin app, sent a message and worked perfect. Please check that bolt shows green for that contact on your end. And test again to see if the error happens every time.
