### ISSUE TITLE
Missing payment_secret in invoices?

### ISSUE THREAD

**Issue by t-bast** [stakwork/sphinx-kotlin#218]
We recently made `payment_secret` mandatory in [eclair](https://github.com/acinq/eclair) (and in [Phoenix](https://phoenix.acinq.co/)). This is important as it fixes real-world attacks where funds could get stolen by the next-to-last node in the route. It has been standardized 18 months ago (https://github.com/lightningnetwork/lightning-rfc/pull/712).

We've had users report that they're now unable to pay to Sphinx Chat, because it seems like your invoices don't provide a `payment_secret`. Can you confirm that this is the case? Is there a reason why this isn't enabled?

**Comment by Evanfeenstra** [comment]
I guess we need to update hosted LND nodes to 0.12 https://github.com/lightningnetwork/lnd/issues/4900

**Comment by t-bast** [comment]
Note that this is slightly different. Even with previous versions of lnd, you should be able to generate invoices containing a `payment_secret` (lnd has implemented that more than a year ago). But it may not be the default behavior. Anyway it's really recommended to update to the latest release in all cases, so let's do that.
