### ISSUE TITLE
can't scan connection QR code on GrapheneOS

### ISSUE THREAD

**Issue by jlopp** [stakwork/sphinx-kotlin#277]
I've installed the latest APK and given camera permissions to the app, but no matter how hard I try to get the QR code to scan, it never gets registered by the app and I must resort to copy/paste of the connection string.

**Comment by gonzaloaune** [comment]
Hi @jlopp I'm running GrapheneOS on a Pixel 4A 5G and the latest Kotlin version https://github.com/stakwork/sphinx-kotlin/releases/tag/1.0.0-alpha18 and I have no problem scanning QR codes. Can you provide more details? Like:
- Kotlin version running
- GrapheneOS version
- Phone brand / version

That might help us identify the issue. Thanks!

**Comment by jlopp** [comment]
Never mind; looks like I was still running the react rather than the kotlin app. However, now I'm getting a "generate token failed" error trying to initialize the client...

**Comment by gonzaloaune** [comment]
@jlopp that could be because the connection to your relay is failing, I'd say decode in base64 the string, check if the IP matches and let me know! Also take a look at the relay logs to try to spot any errors.

**Comment by jlopp** [comment]
base64 decode of the connection string displays the correct IP address

Don't think it's a network issue; there are no other services listening on port 3001 nor do I have a firewall rule set to block it. Am able to open a connection to that IP and port via telnet from my home network.

Could it be macaroon related?
