### ISSUE TITLE
New contact confirmation dialogue

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-kotlin#282]
Now that we have a potential price to add a contact (people page), we need to display a confirmation box in the app between scanning the QR (or tapping a deeplink in the chat) and paying the fee to connect.

**Comment by Antanasijevic** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/13258550/129767051-0f0047f3-1611-497c-831c-07b90b8bc2b7.png)
