### ISSUE TITLE
Send Audio Messages

### ISSUE THREAD

**Issue by kngako** [stakwork/sphinx-kotlin#304]
- Layout for the "hold to record" microphone already there
- Add FooterViewState to RecordAudio
    - Check permissions to record audio (only start recording if they are granted)
    - Records audio into a temp file
    - Audio format to be .amr
    - When recording is cancelled temp file is deleted
    - When recording is done temp file is added as an media attachment and uploaded using the existing logic (might need to generalize the image upload logic)
    - Update the footer to show that recording is in progress.
- All layouts to match iOS version

**Comment by tomastiminskas** [comment]
@kngako swiping left on footer view while recording will cancel audio
