### ISSUE TITLE
Can't login on iPad

### ISSUE THREAD

**Issue by Notaname3** [stakwork/sphinx-kotlin#309]
I downloaded Sphinx chat to my newer model iPad (w/ up to date OS), linked to my private LN node via Sphinx Relay and all seemed well on first launch. However once I logged out and tried to login again I can't enter my PIN number - the touchscreen doesn't appear to operate with the sign in page....even the thumbprint signin doesn't register.

I couldn't find anything in settings that affected this. I tried uninstall/reinstall, tried signing out of VPN but none of this helped.

Wondering if this is a known or common issue, or if anyone else has experienced this?

**Comment by tomastiminskas** [comment]
This was happening on Apple Store version. But it's fixed on TestFlight version.
