### ISSUE TITLE
Can't join any tribes

### ISSUE THREAD

**Issue by satrinity402** [stakwork/sphinx-kotlin#366]
Running the latest Alpha35 on GrapheneOS Android 12 Pixel 5. Was finally able to connect to my node with the latest release, but am unable to join any tribes wither by QR or URL. The error message is always the same: "There was an error joining the tribe. Please try again later"

Things I've tried: 
- Force closing and opening Sphinx kotlin app.
- Rebooting Android device
- Rebooting Pi4 (device that is hosting my LN node)

**Comment by satrinity402** [comment]
Forgot to mention - I am running the universal Kotlin Android app. Not sure if that's the correct one to run on my device or not. Seems to be working fine otherwise.

**Comment by satrinity402** [comment]
Running Raspiblitz. Will look into getting you some logs.

**Comment by satrinity402** [comment]
Of course... once I get logging going, I test joining a Tribe and now it's working... Lol

**Comment by kevkevinpal** [comment]
> Of course... once I get logging going, I test joining a Tribe and now it's working... Lol

Sounds good man :) will close this issue
