### ISSUE TITLE
"Sync more devices" feature not working

### ISSUE THREAD

**Issue by satrinity402** [stakwork/sphinx-kotlin#367]
Running the latest Alpha35 build on an Android 12 GrapheneOS Pixel 5. When I go into Sphinx > Hamburger menu > Profile, I am unable to select "Sync more devices" down at the bottom. So I am unable to pair it to my desktop app.

**Comment by satrinity402** [comment]
Forgot to mention - I am running the universal Kotlin app. Not sure if that's the correct one to run on my device or not. Seems to be working fine otherwise.

**Comment by kevkevinpal** [comment]
Hey @satrinity402 for the sync more devices I think that's just a tag referring to the button below it, you can take the key generated from there and plug it into your desktop app when you select existing user

**Comment by satrinity402** [comment]
My mistake, thank you for the clarification.
