### ISSUE TITLE
Editor box at bottom of screen moves under keyboard if you attempt to edit text

### ISSUE THREAD

**Issue by kirkawolff** [stakwork/sphinx-kotlin#393]
When you start typing, and you get more than one line, then you want to edit (because touchscreens suck for keyboards), when you select an area to edit in the editbox the selected line moves immediately above keyboard with remainder of editbox beneath the keyboard. This makes it impossible to edit anything under the keyboard. The editbox should stay ABOVE the keyboard at all times, not duck under it. Each time you go back to the editbox from the keyboard, it ducks down another line. See attached image.

In order to get your editbox back, you have to touch the back-arrow and then re-select the editbox

I'm using Samsung keyboard v3.3.23.33 on a Samsung Note 8 with Android 9

![image](https://user-images.githubusercontent.com/13596099/150657047-90d09624-ed25-4bc1-bebe-0c2837dad818.png) ![image](https://user-images.githubusercontent.com/13596099/150657051-bca89655-697a-462c-ae7e-da95f0f2cd90.png)

**Comment by tomastiminskas** [comment]
Fixed on #410
