### ISSUE TITLE
Add "share link" to tribe header

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-kotlin#430]
We need an easy way to share an invite to a tribe with another user in sphinx. We have this option in mac desktop, but it's fairly hard to find.

![sphinx thu 17 mar 02 55 30](https://user-images.githubusercontent.com/814886/158893602-8ff922bc-01e1-4be1-afba-a63f379c10e0.jpg)

**Comment by Antanasijevic** [comment]
Seems like the image you posted as example has an error, and it can not be opened, but i think i know what you are referring to. 

On the desktop version we can just add simple share icon next to mute button, something like this
![image](https://user-images.githubusercontent.com/13258550/159541199-142268a5-5b9f-4ced-bae6-0c453f8a832b.png)

When it comes to mobile version, quick solution, based on current state can be making Edit, share and Delete tribe more prominent, like on this example. That way, that subtle menu next to name wont be needed any more. 

![image](https://user-images.githubusercontent.com/13258550/159543013-3dcffb0e-2756-43e4-993b-4a406cbc39ce.png)


Mobile header is too crowded for three icons. Quick solution, based on current state is to add simple additional menu instead mute and call button. Additional menu would contain Mute, call, share and exit tribe options.

![image](https://user-images.githubusercontent.com/13258550/159542252-acb4ffc9-e653-48bc-ad12-9f15e49837e0.png)

**Comment by tomastiminskas** [comment]
This is the menu I was referring to @Antanasijevic :

![Screenshot_20220601-144428_Sphinx Debug](https://user-images.githubusercontent.com/2242281/171469267-0f41aa48-3e71-43d8-8759-3e88ce348067.jpg)
