### ISSUE TITLE
Messages profile pictures clickable

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-kotlin#458]
When tapping on the small profile picture circle for a message on a PRIVATE CONVERSATION (that means not on a tribe) we should take user to the EDIT CONTACT view. Same view we take user to when tapping on CHAT HEADER of a private conversation. 

In addition the header is clickable but the circular profile picture on it is not. That should be fixed so it's clickable as well.

**Comment by MathRoda** [comment]
Hello @tomastiminskas 

this issue now fixed in #485

**Comment by kevkevinpal** [comment]
Closing issue as its now fixed thanks @MathRoda
