### ISSUE TITLE
User not able to Delete or Block contact through chat 

### ISSUE THREAD

**Issue by MathRoda** [stakwork/sphinx-kotlin#496]
@tomastiminskas @kevkevinpal 

i was testing a feature and i need it to delete the contact manually, 
every time i need to do this i have to close the chat and go to `Address Book` to do so, 

i think it's a **better user-experience** to have the ability to delete / block contacts from chat as almost every chatting app has this feature   

|   |   | 
|---|---|
| ![](https://user-images.githubusercontent.com/92212925/192548713-32389a79-4ec3-4731-822f-cf81f19cb685.jpg) | ![](https://user-images.githubusercontent.com/92212925/192548865-33465144-90e8-4be2-8cee-f74abd8f9867.jpg)

**Comment by tomastiminskas** [comment]
@MathRoda sounds like a good addition to me! Let's wait for @kevkevinpal thoughts on this

**Comment by kevkevinpal** [comment]
> @MathRoda sounds like a good addition to me! Let's wait for @kevkevinpal thoughts on this

yup looks good to me too, are we able to add a confirmation modal when we click the delete or block button just to make it a bit resistant to missclicks

**Comment by tomastiminskas** [comment]
@kevkevinpal @MathRoda I think we have the confirmation modal on AddressBook so it will be moving that logic to the ChatViewModel. But yes, definitely we need a confirmation before proceeding

**Comment by kevkevinpal** [comment]
oh wait there is a modal already looks good to me 🚀

**Comment by MathRoda** [comment]
@tomastiminskas @kevkevinpal 
yes i did use a confirmation modal it's the same one as in `Address Book` you can find it in #497 `ChatSideEffect.kt`
