### ISSUE TITLE
[feature] Pinned chat message

### ISSUE THREAD

**Issue by kevkevinpal** [stakwork/sphinx-kotlin#498]
On sphinx-relay the pinned PR's are merged in but the work still needs to be done on the kotlin app

https://github.com/stakwork/sphinx-relay/pull/283
https://github.com/stakwork/sphinx-relay/pull/290
https://github.com/stakwork/sphinx-relay/pull/301

Api endpoint in relay
https://github.com/stakwork/sphinx-relay/blob/master/src/controllers/index.ts#L58
https://github.com/stakwork/sphinx-relay/blob/master/src/controllers/chatTribes.ts#L310

- [x] 1). make Pin show up on long press of message  (@$200k)
        Given: we are a tribe owner
        When: we long press on a message
        Then: we should see the pin button
        
- [x]   2). On press of button save to relay (@$300k)
        Given: we are a tribe owner
        When: we long press on a message and press pin
        Then: we should call relay to save the pinned message PUT /chat_pin/:id
        
- [x]   3). On press of button show at top of chat (@$300k)
        Given: we are a tribe owner
        When: we long press on a message and press pin
        Then: we should see the message showup at the top of the chat
        
- [ ]   4). shows at top of other devices (@$400k)
        Given: we are a member of the tribe
        When: we enter a tribe with a pinned message
        Then: we should see the message showup at the top of the chat

- [x] 5). On click of pin pulls up menu (@$300k)
        Given: we are a tribe owner
        When: we press on the pinned message
        Then: we should see a popup showup below the chat

- [x]   6). Show text on menu (@$100k)
        Given: we are a tribe owner
        When: we press on the pinned message
        Then: we should see a popup showup below the chat with the correct message

- [x]   7). onclick button on menu pop up (@$300k)
        Given: we are a tribe owner
        When: we press on the pinned message popup button
        Then: we remove the pinned message
  - [x]          9). call relay to remove pin (@$300k)
         Given: we are a tribe owner
        When: we press on the pinned message popup button
        Then: we call relay to remove pinned message

- [x] 11). Pinned and unpinned modal building (@$300k)
       build layout of popup modal and when it pops up pinning and unpinning
       
- [x] 12). only allow admin to pin/unpin (@$100k)

more to be added if needed

**Comment by kevkevinpal** [comment]
some things found while working on this

1). seems like the way we have pinned messages implemented on relay we save the message itself and not the chat id, so we might just use the chat id and convert it to a number when using in the app since this will let us know who posted the message and etc
2). we should be saving the message we saved into the db on the application aswell I think we may need to modify `upsertChat` to include a messageId for the pinned message

@mouawiahammo let me know if I'm missing anything that I'm missing

- Also adding another task for the adding of the database stuff in the app since that was not initially scoped (@$300k)

**Comment by MathRoda** [comment]
Yes this all for now,
and i think you meant `messageId`, cause when user open's the chat the `chatId` is already retrieved,
in `Chat` class well be a variable that holds the pined message Id which comes from relay as `String`and would be converted to `Long` as it would be used to `getMessageById` to get access for all the message attribute for the pin message popup

**Comment by kevkevinpal** [comment]
> Yes this all for now, and i think you meant `messageId`, cause when user open's the chat the `chatId` is already retrieved, in `Chat` class well be a variable that holds the pined message Id which comes from relay as `String`and would be converted to `Long` as it would be used to `getMessageById` to get access for all the message attribute for the pin message popup

yup your right I meant message id but yea I think this is a good approach for now

**Comment by MathRoda** [comment]
@tomastiminskas
i think design already exists, but i don't have the material's ( icons... etc)

https://user-images.githubusercontent.com/13258550/155366525-9b3400d3-e79a-4a2f-bd6e-8d0f29f0e54e.png

https://user-images.githubusercontent.com/13258550/155366481-eca9fa0e-2cf1-4c83-8636-2c151f39806f.png

https://user-images.githubusercontent.com/13258550/155368401-11a82759-3cfc-4764-a7ac-839e0595d678.mp4

**Comment by Antanasijevic** [comment]
@tomastiminskas @MathRoda @kevkevinpal Yes, Design exists. We will review it tomorrow morning to see what adjustments are needed, if any. Please, let me know if you have any suggestion.

**Comment by MathRoda** [comment]
https://user-images.githubusercontent.com/92212925/200430904-4866ea40-eb7b-4433-8010-1d9368ec3359.mp4

@tomastiminskas @kevkevinpal 
### Achieved

- pin option only visible for tribe owners 
- pin table stores/updates message id in relay 
- mapping pin value to sphinxDB
- for presentation layer there's 2 methods -> pinMessage / unPinMessage
- implemented pinned message header pop-up
- implemented pinned/unpinned message pop-up view
- implemented a bottom pinned message details -> motion layout 
- parsed data to bottom pinned message details

### Notes
waiting for finalized figma file to adjust design and add the right icons

**Comment by MathRoda** [comment]
Yaaay!🎉
Finally merged. Pleasure to work with you all.
