### ISSUE TITLE
Recommendations default off 

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-kotlin#538]
We should make recommendations off by default. And I think with that we will be disabling actions tracking too. 

We could add a new row on profile with a toggle and an info button to show details on a toast. 

While disabled the feed will show as it shows right now, but instead of "No recommendations found" label, it will says "Enable recommendations from Profile", and a button that will take you there.

**Comment by tomastiminskas** [comment]
@pitoi  let me know if it sounds good. And if you think it's ok to have a info button like a "circular question mark", let me know what text should we show when tapping on it.

**Comment by pitoi** [comment]
Can we hide the recommendation section to users who have it off? 
If that's more work, than lets show a question mark icon with the text:
"Activate recommendations from your profile"

**Comment by tomastiminskas** [comment]
We can hide them of course. And add the toggle on Profile to enable them
