### ISSUE TITLE
New contact process

### ISSUE THREAD

**Issue by pitoi** [stakwork/sphinx-kotlin#574]
When scanning a QR to add a contact, I enter a name for the user but the keyboard remains up and obscures the rest of the form even after pressing the "enter" key.

Second issue:
 - the contact has a green bolt indicating a successful key exchange (I think)
 - a message can be typed and you can press send
 - the outbound message doesn't show up
 - no error msg shows

**Comment by tomastiminskas** [comment]
@pitoi I fixed the first issue. Make the view scrollable and handled the DONE key event. 

Couldn't reproduce the second issue. For me the message shows up when sending.  It must be an edge case where the payment fails, then it doesn't show and we are not showing any error message.

Can you post the pub key of the contact you tested with? So I can try with it
