### ISSUE TITLE
Same seed phrase, different seed bytes send to signer

### ISSUE THREAD

**Issue by irriden** [stakwork/sphinx-kotlin#612]
As of version `1.1.0 (354)`, the flow launched with `Configure Signing Device` displays the same 12-word mnemonic to the user, but sends different bytes to the signer every time the flow is completed.

For reference, these words:
`bike receive cost crouch mango butter top sound surge angry seek left`
should correspond to these bytes sent to the signer:
`5dc83bbd83b2f8587915fcb78d5f84d7b4300668ed86f10e787814448c0ab26f`

@EvanFeenstra suggests to use the `mnemonic_from_entropy` function in [sphinx-ffi](https://github.com/stakwork/sphinx-rs/tree/master/sphinx-ffi).

Last week when we tested this with Paul, the same bytes seemed to be sent to the signer everytime - no issues there. This bug seems to have been introduced very recently.

**Comment by Evanfeenstra** [comment]
Here are the kotlin and swift files for sphinx-ffi https://github.com/stakwork/sphinx-rs/releases

**Comment by tomastiminskas** [comment]
@irriden @Evanfeenstra on iOS we were persisting the seed once generated the first time, and using the same when going through the signer process again. But Paul asked me to generate a new one every time for testing purposes so I did that change. This was on iOS. Just in case that is the cause of the issue you are referring in the ticket. Let me know

**Comment by tomastiminskas** [comment]
@irriden you are right. The issue is on my end. I will upload a new version soon with a fix. So it will generate a new seed phase every time and that one will be shown to the user and sent to the signer.

**Comment by tomastiminskas** [comment]
@irriden @Evanfeenstra new version with the fix will go out soon for internal testing on test-flight. Version 1.1.0 (356)
