### ISSUE TITLE
Add spinner animation upon pull refresh (messages)

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-kotlin#645]
**Task**

Add a spinner animation upon pull refresh of messages. It should happens on each refresh.

**Acceptance Criteria**

- [ ] Assert that pulling refresh each time triggers spinner animation
- [ ] On pull refresh, ensure we retrieve messages via the current endpoint

**Comment by tomsmith8** [comment]
Hey @ariel10aguero !

1) I don't have an android to test. Is this request still an issue? (does it pull refresh and load animation each time?)
2) If not, lets bounty this out - could you provide the exact file location so I can add to the bounty please?

**Comment by ariel10aguero** [comment]
Hey @tomsmith8 yes, on dashboard there is a function to pull refresh which: 

- Refresh the latest contacts
- Refresh the feed content
- Refresh messages

**Comment by tomsmith8** [comment]
Does it have a loading animation on each pull refresh to indicate its loading?

**Comment by ariel10aguero** [comment]
Yes
