### ISSUE TITLE
Push notifications not working

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-kotlin#658]
Firebase messaging miss configured

**Comment by tomastiminskas** [comment]
@tomsmith8 we found that push notifications were not working on the latest releases (google play and GitHub). We found the cause and Alejandro will be releasing a new version with that fixed today. Just FYI in case someone reports it

**Comment by tomsmith8** [comment]
Thanks @tomastiminskas - I'll test Android fixes later this week when I have my device back
