### ISSUE TITLE
Add Privacy Feature for balance

### ISSUE THREAD

**Issue by tomastiminskas** [stakwork/sphinx-kotlin#713]
**Task**

Add ability to hide balance for privacy reasons:

- Tap balance at the top should turn to `*****`. Tapping again should show balance

**Code references:**
`layout_dashboard_header.xml / DashboardFragment.kt`

We should create a new SharedPreferences key to store a boolean that will persist if the balance is visible or hidden. 

**Acceptance Criteria**

- [ ] Tapping a users balance at the top should hide the balance with asterisks ******

**Comment by KotlinGeekDev** [comment]
Hello @tomastiminskas please I would like to work on this.

**Comment by KotlinGeekDev** [comment]
Please @tomsmith8 should the balance in the navigation menu be hidden as well?

**Comment by tomsmith8** [comment]
Good spot, yeah let's add it there too!

**Comment by KotlinGeekDev** [comment]
Hmm @tomsmith8 I am having connection timeout issues while testing my changes(and it seems to be the same with my normal account).

**Comment by tomastiminskas** [comment]
@KotlinGeekDev we had some issues on swarm. Restoring your account should fix it. For that you should go to profile and export your keys tapping on "Backup your keys" button, then deleting app, installing again and restoring going to "Existing user" and then entering your keys string.

**Comment by KotlinGeekDev** [comment]
@tomastiminskas thanks for the info! Will do so.

**Comment by KotlinGeekDev** [comment]
Please, should the denomination be hidden as well? cc @tomsmith8

**Comment by tomsmith8** [comment]
We can keep the denomination `sats`
